;   

INSERT INTO "PUBLIC"."USER" VALUES
(1, 'darjan@gmail.com', '12345', 'darjan');               

INSERT INTO "QUIZ" (id, category, difficulty, enabled, type, user_id, result) VALUES
(1, 'any', 'any', FALSE, 'any', 1, 0.0),
(2, 'any', 'any', FALSE, 'any', 1, 0.0),
(3, 'any', 'any', FALSE, 'any', 1, 0.0),
(4, 'any', 'any', FALSE, 'any', 1, 0.0);        

INSERT INTO "PUBLIC"."QUESTION" VALUES
(1, 'Animals', 1, 'easy', STRINGDECODE('The K\u0101k\u0101p\u014d is a large, flightless, nocturnal parrot native to which country?'), 'multiple', NULL, 1),
(2, 'Science & Nature', 5, 'medium', 'Where did the dog breed &quot;Chihuahua&quot; originate?', 'multiple', NULL, 1),
(3, 'Science: Computers', 9, 'hard', 'Which of these names was an actual codename for a cancelled Microsoft project?', 'multiple', NULL, 1),
(4, 'Entertainment: Video Games', 13, 'easy', 'The &quot;Day of Defeat&quot; series of games take place during which war?', 'multiple', NULL, 1),
(5, 'Celebrities', 17, 'hard', 'How tall is Tom Cruise?', 'multiple', NULL, 1),
(6, 'Entertainment: Music', 21, 'medium', '&quot;Twenty One Pilots&quot; made the song &quot;The Motion&quot; featuring Sampha.', 'boolean', NULL, 1),
(7, 'Entertainment: Music', 23, 'medium', 'What musician made the song &quot;Fuckin` Perfect&quot; in 2010?', 'multiple', NULL, 1),
(8, 'Entertainment: Music', 27, 'easy', 'Who was featured in the song &quot;Words&quot; by Feint? ', 'multiple', NULL, 1),
(9, 'Science & Nature', 31, 'hard', 'Burning which of these metals will produce a bright white flame?', 'multiple', NULL, 1),
(10, 'General Knowledge', 35, 'hard', 'Nephelococcygia is the practice of doing what?', 'multiple', NULL, 1),
(11, 'Sports', 39, 'medium', 'Which German sportswear company&#039;s logo is the &#039;Formstripe&#039;?', 'multiple', NULL, 2),
(12, 'Geography', 43, 'hard', 'What year is on the flag of the US state Wisconsin?', 'multiple', NULL, 2),
(13, 'Entertainment: Video Games', 47, 'easy', 'The end credits sequence in Grand Theft Auto 5 is over half an hour long.', 'boolean', NULL, 2),
(14, 'Entertainment: Music', 49, 'easy', 'Which Disney character sings the song &quot;A Dream is a Wish Your Heart Makes&quot;?', 'multiple', NULL, 2),
(15, 'Science & Nature', 53, 'medium', 'About how old is Earth?', 'multiple', NULL, 2),
(16, 'Entertainment: Video Games', 57, 'medium', 'Which of these games was NOT a Nintendo Switch launch title in the United States? ', 'multiple', NULL, 2),
(17, 'Entertainment: Comics', 61, 'medium', 'In Calvin and Hobbes, what is the name of Susie&#039;s stuffed rabbit?', 'multiple', NULL, 2),
(18, 'Entertainment: Video Games', 65, 'medium', 'What song is played during the ending credits of Guitar Hero: World Tour?', 'multiple', NULL, 2),
(19, 'Entertainment: Television', 69, 'medium', 'Out of the 3 Tots in Tots TV, who speaks French in the UK Version and Spanish in the US Version?', 'multiple', NULL, 2),
(20, 'Entertainment: Japanese Anime & Manga', 73, 'easy', 'What is the name of JoJo&#039;s Bizarre Adventure Part 5?', 'multiple', NULL, 2),
(21, 'Entertainment: Japanese Anime & Manga', 77, 'hard', 'In the anime Initial D, how does Takumi Fujiwara describe a drift?', 'multiple', NULL, 3),
(22, 'Entertainment: Video Games', 81, 'easy', 'What Nationality is D.Va from Overwatch?', 'multiple', NULL, 3),
(23, 'Entertainment: Video Games', 85, 'medium', 'Which of the following characters were considered for inclusion in Super Smash Bros. Melee?', 'multiple', NULL, 3),
(24, 'Entertainment: Film', 89, 'medium', 'Which one of these actors is said to be cut from the film &#039;E.T. the Extra-Terrestrial&#039;?', 'multiple', NULL, 3),
(25, 'Science & Nature', 93, 'medium', 'In Chemistry, how many isomers does Butanol (C4H9OH) have?', 'multiple', NULL, 3),
(26, 'History', 97, 'medium', 'Which building was set aflame on August 24th, 1812?', 'multiple', NULL, 3),
(27, 'Science & Nature', 101, 'medium', 'Deuterium is an isotope of which element?', 'multiple', NULL, 3),
(28, 'Geography', 105, 'medium', 'What is the capital of British Columbia, Canada?', 'multiple', NULL, 3),
(29, 'Vehicles', 109, 'easy', 'The LS2 engine is how many cubic inches?', 'multiple', NULL, 3),
(30, 'Entertainment: Video Games', 113, 'hard', 'In &quot;Starbound&quot;, according to the asset files, the description of the &quot;Erchius Ghost&quot; is the same as which other assets?', 'multiple', NULL, 3),
(31, 'Entertainment: Film', 117, 'easy', 'In the movie &quot;Spaceballs&quot;, what are the Spaceballs attempting to steal from Planet Druidia?', 'multiple', NULL, 4);        
INSERT INTO "PUBLIC"."QUESTION" VALUES
(32, 'Mythology', 121, 'hard', 'Who is the Egyptian god of reproduction and lettuce?', 'multiple', NULL, 4),
(33, 'Celebrities', 125, 'medium', 'Nikki Diamond portrayed which Gladiator in the 1992 TV show &quot;Gladiators&quot;?', 'multiple', NULL, 4),
(34, 'Science: Computers', 129, 'easy', 'In computing, what does LAN stand for?', 'multiple', NULL, 4),
(35, 'General Knowledge', 133, 'easy', 'When someone is cowardly, they are said to have what color belly?', 'multiple', NULL, 4),
(36, 'Sports', 137, 'easy', 'Which African American is in part responsible for integrating  Major League baseball?', 'multiple', NULL, 4),
(37, 'Entertainment: Video Games', 141, 'medium', 'Shang Tsung is a playable character in Mortal Kombat XL.', 'boolean', NULL, 4),
(38, 'Geography', 143, 'medium', 'Which of these American cities has fewer than 1,000,000 people?', 'multiple', NULL, 4),
(39, 'Entertainment: Video Games', 147, 'easy', 'Which of the following was a map that was in Team Fortress 2 at launch?', 'multiple', NULL, 4),
(40, 'Entertainment: Books', 151, 'easy', STRINGDECODE('Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel &quot;The Lord of The Rings&quot;.'), 'boolean', NULL, 4);           


INSERT INTO "PUBLIC"."ANSWER" VALUES
(1, 'New Zealand', 1),
(2, 'South Africa', 1),
(3, 'Australia', 1),
(4, 'Madagascar', 1),
(5, 'Mexico', 2),
(6, 'France', 2),
(7, 'Spain', 2),
(8, 'Russia', 2),
(9, 'Neptune', 3),
(10, 'Enceladus', 3),
(11, 'Pollux', 3),
(12, 'Saturn', 3),
(13, 'World War II', 4),
(14, 'World War I', 4),
(15, 'Vietnam War', 4),
(16, 'Iraq War', 4),
(17, '5&prime; 7&Prime;', 5),
(18, '5&prime; 9&Prime;', 5),
(19, '5&prime; 4&Prime;', 5),
(20, '5&prime; 5&Prime;', 5),
(21, 'False', 6),
(22, 'True', 6),
(23, 'P!nk', 7),
(24, 'Mitis', 7),
(25, 'Adam lambert', 7),
(26, 'Koven', 7),
(27, 'Laura Brehm', 8),
(28, 'Anna Yvette ', 8),
(29, 'Danyka Nadeau', 8),
(30, 'Veela', 8),
(31, 'Magnesium', 9),
(32, 'Copper', 9),
(33, 'Lithium', 9),
(34, 'Lead', 9),
(35, 'Finding shapes in clouds', 10),
(36, 'Sleeping with your eyes open', 10),
(37, 'Breaking glass with your voice', 10),
(38, 'Swimming in freezing water', 10),
(39, 'Puma', 11),
(40, 'Nike', 11),
(41, 'Adidas', 11),
(42, 'Reebok', 11),
(43, '1848', 12),
(44, '1634', 12),
(45, '1783', 12),
(46, '1901', 12),
(47, 'True', 13),
(48, 'False', 13),
(49, 'Cinderella', 14),
(50, 'Belle', 14),
(51, 'Snow White', 14),
(52, 'Pocahontas', 14),
(53, '4.5 Billion Years', 15),
(54, '3.5 Billion Years', 15),
(55, '2.5 Billion Years', 15),
(56, '5.5 Billion Years', 15),
(57, 'Voez', 16),
(58, 'Just Dance 2017', 16),
(59, 'Snipperclips', 16),
(60, 'Fast RMX', 16),
(61, 'Mr. Bun', 17),
(62, 'Mr. Bunbun', 17),
(63, 'Mr. Rabbit', 17),
(64, 'Mr. Hoppy', 17),
(65, 'Dream Theater - Pull Me Under', 18),
(66, 'King Crimson - 21st Century Schizoid Man', 18),
(67, 'Dragonforce - Through The Fire &amp; The Flames', 18),
(68, 'Lynyrd Skynyrd - Free Bird', 18),
(69, 'Tilly', 19),
(70, 'Tom', 19),
(71, 'Tiny', 19),
(72, 'None of the Above', 19),
(73, 'Vento Aureo', 20),
(74, 'Vento Oreo', 20),
(75, 'Vanto Aureo', 20),
(76, 'Vento Eureo', 20),
(77, '&#039;. . . the front tires slide so the car won&#039;t face the inside&#039;', 21),
(78, '&#039;. . . the wheels lose traction, making the car slide sideways&#039;', 21),
(79, '&#039;. . . the car oversteers through a curve, causing it to turn faster&#039;', 21),
(80, '&#039;. . . you turn a lot&#039;', 21),
(81, 'Korean', 22),
(82, 'Japanese', 22),
(83, 'Chinese', 22),
(84, 'Vietnamese ', 22),
(85, 'Lucas', 23),
(86, 'Mega Man', 23),
(87, 'Meta Knight', 23),
(88, 'Diddy Kong', 23),
(89, 'Harrison Ford', 24),
(90, 'Michael J. Fox', 24),
(91, 'Andy Kaufman', 24),
(92, 'Arnold Schwarzenegger', 24),
(93, '4', 25),
(94, '3', 25),
(95, '5', 25),
(96, '6', 25),
(97, 'The White House', 26),
(98, 'Parliament Building', 26),
(99, 'Grand National Assembly Building', 26),
(100, 'Palace of the Nation', 26),
(101, 'Hydrogen', 27),
(102, 'Nitrogen', 27),
(103, 'Helium', 27),
(104, 'Neon', 27),
(105, 'Victoria', 28),
(106, 'Vancouver', 28),
(107, 'Hope', 28),
(108, 'Kelowna', 28),
(109, '364', 29),
(110, '346', 29),
(111, '376', 29),
(112, '402', 29),
(113, 'Spookit', 30),
(114, 'Petricub', 30),
(115, 'Trictus', 30),
(116, 'Pyromantle', 30),
(117, 'Air', 31),
(118, 'The Schwartz', 31),
(119, 'Princess Lonestar', 31),
(120, 'Meatballs', 31),
(121, 'Min', 32),
(122, 'Menu', 32),
(123, 'Mut', 32),
(124, 'Meret', 32),
(125, 'Scorpio', 33),
(126, 'Jet', 33),
(127, 'Nightshade', 33),
(128, 'Falcon', 33),
(129, 'Local Area Network', 34),
(130, 'Long Antenna Node', 34),
(131, 'Light Access Node', 34),
(132, 'Land Address Navigation', 34),
(133, 'Yellow', 35),
(134, 'Green', 35),
(135, 'Red', 35),
(136, 'Blue', 35),
(137, 'Jackie Robinson', 36),
(138, 'Curt Flood', 36),
(139, 'Roy Campanella', 36),
(140, 'Satchell Paige', 36),
(141, 'False', 37),
(142, 'True', 37),
(143, 'San Francisco, California', 38),
(144, 'Phoenix, Arizona', 38),
(145, 'San Antonio, Texas', 38),
(146, 'Philadelphia, Pennsylvania', 38),
(147, 'Gravel Pit', 39),
(148, 'Hoodoo', 39),
(149, 'Gold Rush', 39),
(150, 'Upward', 39),
(151, 'False', 40),
(152, 'True', 40);            

